// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicColl.DBContext;

namespace PicColl.Migrations
{
    [DbContext(typeof(PicDBContext))]
    [Migration("20180831032935_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("PicColl.DBContext.Model.PicInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("ImageLocalPath");

                    b.Property<string>("ImageSiteUrl");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsSuccess");

                    b.Property<DateTime?>("LastDate");

                    b.Property<string>("LocalImageName");

                    b.Property<string>("SrcImageName");

                    b.HasKey("Id");

                    b.ToTable("PicInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
